name: bitsdojo_window
description: A package to help with creating custom windows (custom border, titlebar and minimize/maximize/close buttons) and common window operations (show/hide/position on screen)
version: 0.0.3
homepage: https://www.bitsdojo.com
repository: https://github.com/bitsdojo/bitsdojo_window

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^1.7.3
  ffi: ^0.1.3
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      windows:
        pluginClass: BitsdojoWindowPlugin