name: build-test

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".vscode/**"
      - "CHANGELOG.md"
      - "LICENSE"
      - "README.md"
      - "resources/**"
      - "**/CHANGELOG.md"
      - "**/LICENSE"
      - "**/README.md"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "CHANGELOG.md"
      - "LICENSE"
      - "README.md"
      - "resources/**"
      - "**/CHANGELOG.md"
      - "**/LICENSE"
      - "**/README.md"
  workflow_dispatch:

concurrency:
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu, windows, macos]
        include:
          - runner: ubuntu
            target: linux
          - runner: windows
            target: windows
          - runner: macos
            target: macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Setup Ninja and GTK3 toolchain (Only Linux)
        if: matrix.runner == 'ubuntu'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Fetch dependencies
        working-directory: bitsdojo_window/example
        run: flutter pub get

      - name: Run flutter build ${{ matrix.target }}
        working-directory: bitsdojo_window/example
        run: flutter build ${{ matrix.target }} --release -v

      - name: Archive artifacts (Linux)
        if: matrix.runner == 'ubuntu'
        uses: actions/upload-artifact@v3
        with:
          name: bitsdojo_window_example_${{ matrix.runner }}
          path: bitsdojo_window/example/build/linux/x64/release/bundle/

      - name: Archive artifacts (Windows)
        if: matrix.runner == 'windows'
        uses: actions/upload-artifact@v3
        with:
          name: bitsdojo_window_example_${{ matrix.runner }}
          path: bitsdojo_window/example/build/windows/runner/Release/bitsdojo_window_example.exe

      - name: Archive artifacts (macOS)
        if: matrix.runner == 'macos'
        uses: actions/upload-artifact@v3
        with:
          name: bitsdojo_window_example_${{ matrix.runner }}
          path: bitsdojo_window/example/build/macos/Build/Products/Release/bitsdojo_window_example.app
